name: Build Front & Back to docker hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connexion Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push BACK
        uses: docker/build-push-action@v5
        with:
          context: ./back_front/back
          file: ./back_front/back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/monapp-back:latest

      - name: Build & Push FRONT
        uses: docker/build-push-action@v5
        with:
          context: ./back_front/front
          file: ./back_front/front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/monapp-front:latest